FROM debian@sha256:731dd1380d6a8d170a695dbeb17fe0eade0e1c29f654cf0a3a07f372191c3f4b
LABEL maintainer="githubfoam"

ENV NAGIOS_HOME=/opt/nagios
ENV NAGIOS_USER=nagios
ENV NAGIOS_GROUP=nagios
ENV NAGIOS_CMDUSER=nagios
ENV NAGIOS_CMDGROUP=nagios
ENV NAGIOS_FQDN=nagios.example.com
ENV NAGIOSADMIN_USER=nagiosadmin
ENV NAGIOSADMIN_PASS=nagios
ENV APACHE_RUN_USER=nagios
ENV APACHE_RUN_GROUP=nagios
ENV NAGIOS_TIMEZONE=UTC
ENV DEBIAN_FRONTEND=noninteractive
ENV NG_NAGIOS_CONFIG_FILE=${NAGIOS_HOME}/etc/nagios.cfg
ENV NG_CGI_DIR=${NAGIOS_HOME}/sbin
ENV NG_WWW_DIR=${NAGIOS_HOME}/share/nagiosgraph
ENV NG_CGI_URL=/cgi-bin
ENV NAGIOS_BRANCH=nagios-4.5.9
ENV NAGIOS_PLUGINS_BRANCH=release-2.4.12
ENV NRPE_BRANCH=nrpe-4.1.3
ENV NCPA_BRANCH=v3.1.3
ENV NSCA_BRANCH=nsca-2.10.2
ENV NAGIOSTV_VERSION=0.9.2

# install dependencies
RUN apt-get update && \
    echo "postfix postfix/main_mailer_type string 'Internet Site'" | debconf-set-selections && \
    echo "postfix postfix/mynetworks string '127.0.0.0/8'" | debconf-set-selections && \
    echo "postfix postfix/mailname string ${NAGIOS_FQDN}" | debconf-set-selections && \
    apt-get install -y \
        apache2 \
        apache2-utils \
        autoconf \
        automake \
        bc \
        bsd-mailx \
        build-essential \
        dnsutils \
        fping \
        gettext \
        git \
        gperf \
        iputils-ping \
        jq \
        libapache2-mod-php \
        libcache-memcached-perl \
        libcgi-pm-perl \
        libcrypt-des-perl \
        libcrypt-rijndael-perl \
        libcrypt-x509-perl \
        libdbd-mysql-perl \
        libdbd-pg-perl \
        libdbi-dev \
        libdbi-perl \
        libdigest-hmac-perl \
        libfreeradius-dev \
        libgd-dev \
        libgd-perl \
        libjson-perl \
        libldap2-dev \
        monitoring-plugins \
        libmariadb-dev \
        libnagios-object-perl \
        libnet-snmp-perl \
        libnet-tftp-perl \
        libnet-xmpp-perl \
        libpq-dev \
        libradsec-dev \
        libredis-perl \
        rrdtool  \
        librrds-perl \
        libssl-dev \
        libtext-glob-perl \
        libwww-perl \
        m4 \
        netcat-traditional \
        parallel \
        php-cli \
        php-gd \
        postfix \
        python3 \
        python3-venv \
        python3-pip \
        rsync \
        rsyslog \
        runit \
        smbclient \
        snmp \
        snmpd \
        unzip \
        wget \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

    # Create Nagios users and groups
RUN (egrep -i "^${NAGIOS_GROUP}" /etc/group || groupadd $NAGIOS_GROUP) && \
    (egrep -i "^${NAGIOS_CMDGROUP}" /etc/group || groupadd $NAGIOS_CMDGROUP) && \
    (id -u $NAGIOS_USER || useradd --system -d $NAGIOS_HOME -g $NAGIOS_GROUP $NAGIOS_USER) && \
    (id -u $NAGIOS_CMDUSER || useradd --system -d $NAGIOS_HOME -g $NAGIOS_CMDGROUP $NAGIOS_CMDUSER) 


# Install qstat
RUN cd /tmp && \
    git clone https://github.com/multiplay/qstat.git && \
    cd qstat && ./autogen.sh && ./configure && make && make install && make clean && \
    cd /tmp && rm -rf qstat
    
# Install Nagios Core
RUN cd /tmp && \
    git clone https://github.com/NagiosEnterprises/nagioscore.git -b $NAGIOS_BRANCH && \
    cd nagioscore && \
    ./configure \
        --prefix=${NAGIOS_HOME} \
        --exec-prefix=${NAGIOS_HOME} \
        --enable-event-broker \
        --with-command-user=${NAGIOS_CMDUSER} \
        --with-command-group=${NAGIOS_CMDGROUP} \
        --with-nagios-user=${NAGIOS_USER} \
        --with-nagios-group=${NAGIOS_GROUP} && \
    make all && make install && make install-config && make install-commandmode && make install-webconf && make clean && \
    cd /tmp && rm -rf nagioscore
